[project]
name = "iniad-cs2-exercise"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "mst-mkt", email = "s1f102303057@iniad.org" }
]
dependencies = [
    "django>=4.2.8",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "django-stubs>=4.2.6",
    "ruff>=0.1.7",
    "mypy>=1.7.1",
]

[tool.hatch.metadata]
allow-direct-references = true
