name: Lint and Type check

on: [push]

jobs:
    lint-and-typecheck:
        name: Lint and Typecheck
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}
            - name: Install Rye
              uses: baptiste0928/cargo-install@v2
              with:
                  crate: rye
                  git: https://github.com/mitsuhiko/rye
                  branch: main
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20
            - name: Install Python Dependencies
              run: rye sync
            - name: Install Node.js Dependencies
              uses: pnpm/action-setup@v2
              with:
                  version: 8
                  run_install: |
                      - args: [--frozen-lockfile]
            - name: Lint
              run: rye run lint
            - name: TypeCheck
              run: rye run typecheck
